### ISSUE TITLE
关于论文中“semantic attention is essential while neighbor attention is not necessary” 的讨论

### ISSUE THREAD

**Issue by OnlineWaAndRe** [ICT-GIMLab/SeHGNN#11]
作者您好，我不太清楚这句话，您所说的这个neighbor attention is not necessary, 这个“neighbor attention”是元路径的邻居呢？还是普通意义上的与结点目标相连的邻居。您做的相关实验是在HAN上面的，HAN里面的neighbor attention 是元路径邻居的。
![image](https://github.com/ICT-GIMLab/SeHGNN/assets/48265296/bc33d4b3-f739-4fc3-b6c2-7e0ee471aa88)

**Comment by Yangxc13** [comment]
元路径邻居，和HAN一样。SeHGNN论文里Motivation章节提到：
These attentions can be classified into two types: **neighbor attention within neighbors of the same relation** and *semantic attention* among different relations.

**Comment by OnlineWaAndRe** [comment]
好的 谢谢






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ICT-GIMLab/SeHGNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月24日(星期二) 晚上10:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ICT-GIMLab/SeHGNN] 关于论文中“semantic attention is essential while neighbor attention is not necessary” 的讨论 (Issue #11)





 
元路径邻居，和HAN一样。SeHGNN论文里Motivation章节提到：
 These attentions can be classified into two types: neighbor attention within neighbors of the same relation and semantic attention among different relations.
