### ISSUE TITLE
请问关于data/complex_nars中4个文件的作用？

### ISSUE THREAD

**Issue by fanli221** [ICT-GIMLab/SeHGNN#13]
请问关于data/complex_nars中4个文件的作用？以及该如何使用？

**Comment by Yangxc13** [comment]
针对 ogbn_mag 数据集，用自监督（链接预测）方法生成每个结点额外的初始 embedding。使用方法参见 ogbn/Readme.md

**Comment by fanli221** [comment]
感谢回复！
