### ISSUE TITLE
打扰了，请教下运行时间和可视化问题！

### ISSUE THREAD

**Issue by gaoshihao333** [ICT-GIMLab/SeHGNN#15]
再次打扰，望大佬解惑！ 请问，论文中的运行时间是单指 for epoch in (args.epoch)： 中每个epoch的时间吗？ 不算前面一些预处理啥的，对吗？

大佬，尽管您的论文里面没有做可视化（实验已经很充分了），但是我想问下，异质图相关论文里面的嵌入可视化是针对测试集的可视化结果吗？还是整个数据集的？我看论文好像都没有说明，大佬能解惑一下吗？

如有时间解惑，万分感激! 祝好！

**Comment by Yangxc13** [comment]
1. 论文里的运行时间是单指每个epoch的时间，没有计算预处理。
2. 我没有做过可视化工作，所以不清楚其他论文里的embedding的可视化的执行过程。
注工作学习顺利～

**Comment by gaoshihao333** [comment]
> 1. 论文里的运行时间是单指每个epoch的时间，没有计算预处理。
> 2. 我没有做过可视化工作，所以不清楚其他论文里的embedding的可视化的执行过程。
>    注工作学习顺利～

感谢！Have a good day！
