### ISSUE TITLE
the module “sparse_tools“ is missing

### ISSUE THREAD

**Issue by ZeroerWiser** [ICT-GIMLab/SeHGNN#16]
I can't find the file or module of sparse_tools, which is yor import in your code of "main.py"

**Comment by Yangxc13** [comment]
Thank you for your attention.
This module needs to be installed manually. Please consult the readme file for instructions. [https://github.com/ICT-GIMLab/SeHGNN?tab=readme-ov-file#2-other-dependencies](https://github.com/ICT-GIMLab/SeHGNN?tab=readme-ov-file#2-other-dependencies)
