### ISSUE TITLE
对于聚合过程的疑问

### ISSUE THREAD

**Issue by wangyili00** [ICT-GIMLab/SeHGNN#17]
您好，感谢您的代码分享，我想问一下在pre-processing step的过程中，注意到每种类型的点的特征维度不一致，所以在这里并没有聚合到target节点中，只是收集某个节点的所有src 节点的特征并做了一个平均对吗？

**Comment by heamina** [comment]
> 您好，感谢您的代码分享，我想问一下在pre-processing step的过程中，注意到每种类型的点的特征维度不一致，所以在这里并没有聚合到target节点中，只是收集某个节点的所有src 节点的特征并做了一个平均对吗？

嘿你好，我看作者的代码中是这么写的，只进行了邻居节点的平均，然后通过MLP将不同的邻居特征维度映射为一个相同的维度

**Comment by Yangxc13** [comment]
是的，正如 heamina 同学所言。同种node_type的邻居节点做平均聚合，然后用MLP映射到相同维度。

**Comment by XILOUYUE7** [comment]
您好，我对您的研究很感兴趣，但是我在看代码时遇见一些问题，想向您请教一下，在论文中的Finding 2表明，浅层长metapath对比多层短metapath效果要好，在代码中注意到好像只进行了1-hop的metapath的节点聚合，比如（P-A，P-S），当然更可能是我的理解出现偏差，按照我现在的理解，难道不是构建多种metapath,比如P-A， P-S， P-A-P， P-S-P， P-A-P-A-P， P-S-P-S-P的metapath，然后分别进行节点的聚合，再映射到相同维度的token经过transformer进行语义融合吗，但是我在代码中未找到P-A-P， P-S-P， P-A-P-A-P， P-S-P-S-P构建的部分，可能是以另一种我没理解的方法构建的，还请不吝赐教，感谢

**Comment by heamina** [comment]
> 您好，我对您的研究很感兴趣，但是我在看代码时遇见一些问题，想向您请教一下，在论文中的Finding 2表明，浅层长metapath对比多层短metapath效果要好，在代码中注意到好像只进行了1-hop的metapath的节点聚合，比如（P-A，P-S），当然更可能是我的理解出现偏差，按照我现在的理解，难道不是构建多种metapath,比如P-A， P-S， P-A-P， P-S-P， P-A-P-A-P， P-S-P-S-P的metapath，然后分别进行节点的聚合，再映射到相同维度的token经过transformer进行语义融合吗，但是我在代码中未找到P-A-P， P-S-P， P-A-P-A-P， P-S-P-S-P构建的部分，可能是以另一种我没理解的方法构建的，还请不吝赐教，感谢

这个元路径的构造有个函数实现的，比如dblp数据集它的目标类型节点是a，跳数是2，那么函数生成的元路径就是【a,ap,apa,apt,apc 】这五个特征矩阵，然后用于后续的特征融合

**Comment by XILOUYUE7** [comment]
@heamina 明白了，非常感谢。
