### ISSUE TITLE
关于目标节点的问题

### ISSUE THREAD

**Issue by XILOUYUE7** [ICT-GIMLab/SeHGNN#18]
您好，非常感谢分享代码，关于代码我想请问一下倘若想在同一个训练过程中获取多种目标节点的表征，比如在DBLP数据集中同一个训练过程中获取A，P，T三种类型节点的表征，有什么建议吗

**Comment by Yangxc13** [comment]
同学你好，你指的是每个metapath对应的节点特征嘛？如果是的话，应该对应的是这里的 raw_feats
https://github.com/ICT-GIMLab/SeHGNN/blob/e92bd37d0b803457339555684f139b4c8f3e160d/hgb/main.py#L78
