### ISSUE TITLE
problem of dgl version

### ISSUE THREAD

**Issue by JayKuo1** [ICT-GIMLab/SeHGNN#7]
Your work is great. But I found some problem when I run the train_graph_emb.sh in data/complex_nars: `AttributeError: module 'dgl' has no attribute 'DGLGraphStale'.` It looks like a version problem.

**Comment by Yangxc13** [comment]
Sorry for late response. It looks that `dgl.DGLGraphStale` has been removed for dgl >= 1.0. We will fix it or note this version requirement in the next update soon.
