### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by knightzhong** [ICT-GIMLab/SeHGNN#8]
Thank you for sharing. I noticed that the download link for the dataset in the readme is no longer available. Could you please provide an alternative link?

**Comment by Yangxc13** [comment]
Sorry for late response. It seems that HGB team no longer maintains their data link. Please download through [this link](https://drive.google.com/file/d/1KS2GLBjMPeK127KNt-o8s-nxMIwrTbjd) temporarily.

**Comment by amblee0306** [comment]
Can I check if label.dat.test_full in the dataset refers to the full test set that the task is being evaluated on?

**Comment by Yangxc13** [comment]
No, the local evaluation only performs on half of the test set.

**Comment by amblee0306** [comment]
okays. To clarify again, the current version of the code is only on a partial dataset even when the full test sets of HGB have been released. Thanks! Also can I check if you all have evaluated your model's result on the heterogeneous datasets used by GTN instead of HGB?

**Comment by Yangxc13** [comment]
Yes. Sorry I have left this laboratory and may no longer carry out research in this field. But I think it would be easy for you to make adjustments to conduct a local evaluation on the full test sets. Additionally, I did not evaluate this model using the dataset configurations of GTN.

**Comment by amblee0306** [comment]
okays, thanks for your reply!
