### ISSUE TITLE
About the training of SeHGNN

### ISSUE THREAD

**Issue by zzyzeyuan** [ICT-GIMLab/SeHGNN#9]
Hi,

I enable GPU on training with `--gpu 1`, but the occupancy rate of GPU is very low, thus the training speed is quite slow.

I don't know if this is normal for SeHGNN, and how to solve this problem?

**Comment by Yangxc13** [comment]
Hello, could you please provide additional details regarding this matter? For instance, could you specify the dataset you are referring to? What is the command you are using? When you mention 'the occupancy rate of GPU is very low,' are you referring to low GPU memory occupancy or low utilization? 

It would be better if you could provide some images illustrating your issue.

**Comment by zzyzeyuan** [comment]
Thanks for your reply.

The training speeds on IMDB and ACM are both as efficient as you reported in your paper.

But when I run the command on Freebase dataset as follows
```
python main.py --stage 200 --dataset Freebase --act leaky-relu --n-layers-1 2 --n-layers-2 4 --num-hops 2 --num-label-hops 3 --hidden 512 --embed-size 512 --residual --lr 3e-4 --weight-decay 1e-4 --batch-size 30000 --bns --amp --seeds 1 --gpu 1
```
The the occupancy rate of GPU is very low, and the converge time is about 400 seconds. 
So, we don't know whether the converge time on Freebase is as expected as yours.

**Comment by Yangxc13** [comment]
This duration (400 seconds) is normal, as the Freebase dataset is large and employs a greater number of metapaths (refer to the Appendix of this paper) compared to other datasets.

Furthermore, if you're executing this command for the first time, the initial pre-processing step will be time-consuming and doesn't utilize GPUs. This pre-processing step creates adjacency matrices for numerous metapaths and stores temporary files in the './Freebase_adjs' directory. When you run the command for the second time, it will simply load the pre-processing results from those temporary files. At that point, you should observe a higher GPU utilization.

**Comment by zzyzeyuan** [comment]
Got it.

Thank you very much. I' ll close this issue.
